package com.student.emailtool.mailer;

import com.student.emailtool.model.Contact;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class Mailer {
    private static final DateTimeFormatter OUTBOX_TIME_FORMAT = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss_SSS");

    public static void main(String[] args) {
        try {
            CliArgs cliArgs = parseArgs(args);
            Mailer mailer = new Mailer();

            List<String> recipients = mailer.loadEmailList(Paths.get(cliArgs.emailListFile));
            Set<String> blacklist = mailer.loadBlacklist(cliArgs.blacklistFile == null ? null : Paths.get(cliArgs.blacklistFile));
            Map<String, Contact> contactsByEmail = mailer.loadContacts(Paths.get(cliArgs.contactsCsvFile));
            Template template = mailer.loadTemplate(Paths.get(cliArgs.templateFile));

            if (cliArgs.previewMode) {
                mailer.generatePreviewFiles(recipients, blacklist, contactsByEmail, template);
                System.out.println("Preview completed. Files saved to outbox/");
                return;
            }

            mailer.sendAllEmails();
            System.out.println("Send mode selected. sendAllEmails() is currently a placeholder.");
        } catch (IllegalArgumentException e) {
            System.err.println("Argument error: " + e.getMessage());
            printUsage();
        } catch (NoSuchFileException e) {
            System.err.println("Mailer failed: file not found -> " + e.getFile());
        } catch (Exception e) {
            System.err.println("Mailer failed: " + e.getMessage());
        }
    }

    private static CliArgs parseArgs(String[] args) {
        CliArgs cliArgs = new CliArgs();

        for (int i = 0; i < args.length; i++) {
            String arg = args[i];
            switch (arg) {
                case "-e":
                    cliArgs.emailListFile = requireValue(args, ++i, "-e requires <emails.txt>");
                    break;
                case "-c":
                    cliArgs.contactsCsvFile = requireValue(args, ++i, "-c requires <contacts.csv>");
                    break;
                case "-t":
                    cliArgs.templateFile = requireValue(args, ++i, "-t requires <template.txt>");
                    break;
                case "--preview":
                    cliArgs.previewMode = true;
                    break;
                case "--send":
                    cliArgs.sendMode = true;
                    break;
                case "--log":
                    cliArgs.logFile = requireValue(args, ++i, "--log requires <sent.log>");
                    break;
                case "--blacklist":
                    cliArgs.blacklistFile = requireValue(args, ++i, "--blacklist requires <file>");
                    break;
                default:
                    throw new IllegalArgumentException("Unknown argument: " + arg);
            }
        }

        if (cliArgs.emailListFile == null || cliArgs.contactsCsvFile == null || cliArgs.templateFile == null) {
            throw new IllegalArgumentException("-e, -c, -t are required.");
        }
        if (cliArgs.previewMode == cliArgs.sendMode) {
            throw new IllegalArgumentException("Choose exactly one mode: --preview or --send.");
        }

        return cliArgs;
    }

    private static String requireValue(String[] args, int index, String messageIfMissing) {
        if (index >= args.length) {
            throw new IllegalArgumentException(messageIfMissing);
        }
        return args[index];
    }

    private static void printUsage() {
        System.out.println("Usage:");
        System.out.println("  -e <emails.txt>      recipient email list file");
        System.out.println("  -c <contacts.csv>    contacts file generated by Clean");
        System.out.println("  -t <template.txt>    template file with Subject on first line");
        System.out.println("  --preview            preview mode, writes drafts into outbox/");
        System.out.println("  --send               actual send mode");
        System.out.println("  --log <sent.log>     send log file path");
        System.out.println("  --blacklist <file>   optional blacklist file");
    }

    private List<String> loadEmailList(Path emailsFile) throws IOException {
        List<String> lines = Files.readAllLines(emailsFile, StandardCharsets.UTF_8);
        List<String> result = new ArrayList<>();
        for (String line : lines) {
            String email = line.trim();
            if (!email.isEmpty()) {
                result.add(email);
            }
        }
        return result;
    }

    private Set<String> loadBlacklist(Path blacklistFile) throws IOException {
        Set<String> blacklist = new HashSet<>();
        if (blacklistFile == null) {
            return blacklist;
        }

        List<String> lines = Files.readAllLines(blacklistFile, StandardCharsets.UTF_8);
        for (String line : lines) {
            String email = line.trim().toLowerCase();
            if (!email.isEmpty()) {
                blacklist.add(email);
            }
        }
        return blacklist;
    }

    private Map<String, Contact> loadContacts(Path contactsCsv) throws IOException {
        List<String> lines = Files.readAllLines(contactsCsv, StandardCharsets.UTF_8);
        Map<String, Contact> contactsByEmail = new HashMap<>();

        for (int lineNo = 1; lineNo <= lines.size(); lineNo++) {
            String rawLine = lines.get(lineNo - 1);
            String line = rawLine.trim();
            if (line.isEmpty()) {
                continue;
            }

            String[] parts = line.split(",", -1);
            if (parts.length != 3) {
                throw new IOException("Invalid contacts CSV at line " + lineNo + ": expected Name,Email,City");
            }

            String name = parts[0].trim();
            String email = parts[1].trim();
            String city = parts[2].trim();

            if ("Email".equalsIgnoreCase(email) && "Name".equalsIgnoreCase(name)) {
                continue;
            }
            if (email.isEmpty()) {
                continue;
            }

            Contact contact = new Contact(name, email, city);
            contactsByEmail.put(email.toLowerCase(), contact);
        }

        return contactsByEmail;
    }

    private Template loadTemplate(Path templateFile) throws IOException {
        List<String> lines = Files.readAllLines(templateFile, StandardCharsets.UTF_8);
        if (lines.isEmpty()) {
            throw new IllegalArgumentException("Template file is empty.");
        }

        String firstLine = lines.get(0);
        String prefix = "Subject:";
        if (!firstLine.regionMatches(true, 0, prefix, 0, prefix.length())) {
            throw new IllegalArgumentException("Template first line must start with 'Subject:'.");
        }

        String subjectTemplate = firstLine.substring(prefix.length()).trim();
        String bodyTemplate = String.join(System.lineSeparator(), lines.subList(1, lines.size()));
        return new Template(subjectTemplate, bodyTemplate);
    }

    private PreparedEmail prepareEmail(Contact contact, String subjectTemplate, String bodyTemplate) {
        String name = safe(contact.getName());
        String email = safe(contact.getEmail());
        String city = safe(contact.getCity());

        String subject = replacePlaceholders(subjectTemplate, name, email, city);
        String body = replacePlaceholders(bodyTemplate, name, email, city);
        return new PreparedEmail(subject, body);
    }

    private String replacePlaceholders(String template, String name, String email, String city) {
        return safe(template)
                .replace("{name}", name)
                .replace("{email}", email)
                .replace("{city}", city);
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }

    private void generatePreviewFiles(List<String> recipients,
                                      Set<String> blacklist,
                                      Map<String, Contact> contactsByEmail,
                                      Template template) throws IOException {
        Path outboxDir = Paths.get("outbox");
        Files.createDirectories(outboxDir);

        int counter = 0;
        for (String recipientEmail : recipients) {
            String key = recipientEmail.toLowerCase();
            if (blacklist.contains(key)) {
                continue;
            }

            Contact contact = contactsByEmail.get(key);
            if (contact == null) {
                continue;
            }

            PreparedEmail email = prepareEmail(contact, template.subjectTemplate, template.bodyTemplate);
            String timestamp = LocalDateTime.now().format(OUTBOX_TIME_FORMAT);
            String sanitized = recipientEmail.replaceAll("[^A-Za-z0-9._-]", "_");
            String fileName = "to_" + sanitized + "_" + timestamp + "_" + counter + ".txt";

            String content = "To: " + recipientEmail + System.lineSeparator()
                    + "Subject: " + email.subject + System.lineSeparator()
                    + System.lineSeparator()
                    + email.body;
            Files.writeString(outboxDir.resolve(fileName), content, StandardCharsets.UTF_8);
            counter++;
        }
    }

    public void sendAllEmails() {
        // Placeholder: actual send flow will be implemented in the next step.
    }

    private static class CliArgs {
        private String emailListFile;
        private String contactsCsvFile;
        private String templateFile;
        private boolean previewMode;
        private boolean sendMode;
        private String logFile;
        private String blacklistFile;
    }

    private static class Template {
        private final String subjectTemplate;
        private final String bodyTemplate;

        private Template(String subjectTemplate, String bodyTemplate) {
            this.subjectTemplate = subjectTemplate;
            this.bodyTemplate = bodyTemplate;
        }
    }

    private static class PreparedEmail {
        private final String subject;
        private final String body;

        private PreparedEmail(String subject, String body) {
            this.subject = subject;
            this.body = body;
        }
    }
}
