package com.student.emailtool.mailer;

import com.student.emailtool.model.Contact;
import com.student.emailtool.model.SendLog;
import jakarta.mail.Authenticator;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.LockSupport;

public class Mailer {
    private static final long MIN_SEND_INTERVAL_MS = 501;
    private static final int MAX_RETRIES = 2;
    private static final long RETRY_INTERVAL_MS = 3000;

    public static void main(String[] args) {
        try {
            CliArgs cliArgs = parseArgs(args);
            Mailer mailer = new Mailer();

            List<String> recipients = mailer.loadEmailList(Paths.get(cliArgs.emailListFile));
            Set<String> blacklist = mailer.loadBlacklist(cliArgs.blacklistFile == null ? null : Paths.get(cliArgs.blacklistFile));
            Map<String, Contact> contactsByEmail = mailer.loadContacts(Paths.get(cliArgs.contactsCsvFile));
            Template template = mailer.loadTemplate(Paths.get(cliArgs.templateFile));

            if (cliArgs.previewMode) {
                mailer.generatePreviewFiles(recipients, blacklist, contactsByEmail, template);
                System.out.println("Preview completed. Files saved to outbox/");
                return;
            }

            mailer.sendAllEmails(recipients, blacklist, contactsByEmail, template, Paths.get(cliArgs.logFile));
            System.out.println("Send completed. Logs appended to " + cliArgs.logFile);
        } catch (IllegalArgumentException e) {
            System.err.println("Argument error: " + e.getMessage());
            printUsage();
        } catch (NoSuchFileException e) {
            System.err.println("Mailer failed: file not found -> " + e.getFile());
        } catch (Exception e) {
            System.err.println("Mailer failed: " + e.getMessage());
        }
    }

    private static CliArgs parseArgs(String[] args) {
        CliArgs cliArgs = new CliArgs();

        for (int i = 0; i < args.length; i++) {
            String arg = args[i];
            switch (arg) {
                case "-e":
                    cliArgs.emailListFile = requireValue(args, ++i, "-e requires <emails.txt>");
                    break;
                case "-c":
                    cliArgs.contactsCsvFile = requireValue(args, ++i, "-c requires <contacts.csv>");
                    break;
                case "-t":
                    cliArgs.templateFile = requireValue(args, ++i, "-t requires <template.txt>");
                    break;
                case "--preview":
                    cliArgs.previewMode = true;
                    break;
                case "--send":
                    cliArgs.sendMode = true;
                    break;
                case "--log":
                    cliArgs.logFile = requireValue(args, ++i, "--log requires <sent.log>");
                    break;
                case "--blacklist":
                    cliArgs.blacklistFile = requireValue(args, ++i, "--blacklist requires <file>");
                    break;
                default:
                    throw new IllegalArgumentException("Unknown argument: " + arg);
            }
        }

        if (cliArgs.emailListFile == null || cliArgs.contactsCsvFile == null || cliArgs.templateFile == null) {
            throw new IllegalArgumentException("-e, -c, -t are required.");
        }
        if (cliArgs.previewMode == cliArgs.sendMode) {
            throw new IllegalArgumentException("Choose exactly one mode: --preview or --send.");
        }
        if (cliArgs.sendMode && cliArgs.logFile == null) {
            throw new IllegalArgumentException("--send requires --log <sent.log>.");
        }

        return cliArgs;
    }

    private static String requireValue(String[] args, int index, String messageIfMissing) {
        if (index >= args.length) {
            throw new IllegalArgumentException(messageIfMissing);
        }
        return args[index];
    }

    private static void printUsage() {
        System.out.println("Usage:");
        System.out.println("  -e <emails.txt>      recipient email list file");
        System.out.println("  -c <contacts.csv>    contacts file generated by Clean");
        System.out.println("  -t <template.txt>    template file with Subject on first line");
        System.out.println("  --preview            preview mode, writes drafts into outbox/");
        System.out.println("  --send               actual send mode");
        System.out.println("  --log <sent.log>     send log file path");
        System.out.println("  --blacklist <file>   optional blacklist file");
    }

    private List<String> loadEmailList(Path emailsFile) throws IOException {
        List<String> lines = Files.readAllLines(emailsFile, StandardCharsets.UTF_8);
        List<String> result = new ArrayList<>();
        for (String line : lines) {
            String email = line.trim();
            if (!email.isEmpty()) {
                result.add(email);
            }
        }
        return result;
    }

    private Set<String> loadBlacklist(Path blacklistFile) throws IOException {
        Set<String> blacklist = new HashSet<>();
        if (blacklistFile == null) {
            return blacklist;
        }

        if (!Files.exists(blacklistFile)) {
            System.err.println("Warning: blacklist file not found, continue without blacklist -> " + blacklistFile);
            return blacklist;
        }

        List<String> lines = Files.readAllLines(blacklistFile, StandardCharsets.UTF_8);
        for (String line : lines) {
            String email = line.trim().toLowerCase();
            if (!email.isEmpty()) {
                blacklist.add(email);
            }
        }
        return blacklist;
    }

    private Map<String, Contact> loadContacts(Path contactsCsv) throws IOException {
        List<String> lines = Files.readAllLines(contactsCsv, StandardCharsets.UTF_8);
        Map<String, Contact> contactsByEmail = new HashMap<>();

        for (int lineNo = 1; lineNo <= lines.size(); lineNo++) {
            String rawLine = lines.get(lineNo - 1);
            String line = rawLine.trim();
            if (line.isEmpty()) {
                continue;
            }

            String[] parts = line.split(",", -1);
            if (parts.length != 3) {
                throw new IOException("Invalid contacts CSV at line " + lineNo + ": expected Name,Email,City");
            }

            String name = parts[0].trim();
            String email = parts[1].trim();
            String city = parts[2].trim();

            if ("Email".equalsIgnoreCase(email) && "Name".equalsIgnoreCase(name)) {
                continue;
            }
            if (email.isEmpty()) {
                continue;
            }

            Contact contact = new Contact(name, email, city);
            contactsByEmail.put(email.toLowerCase(), contact);
        }

        return contactsByEmail;
    }

    private Template loadTemplate(Path templateFile) throws IOException {
        List<String> lines = Files.readAllLines(templateFile, StandardCharsets.UTF_8);
        if (lines.isEmpty()) {
            throw new IllegalArgumentException("Template file is empty.");
        }

        String firstLine = lines.get(0);
        String prefix = "Subject:";
        if (!firstLine.regionMatches(true, 0, prefix, 0, prefix.length())) {
            throw new IllegalArgumentException("Template first line must start with 'Subject:'.");
        }

        String subjectTemplate = firstLine.substring(prefix.length()).trim();
        String bodyTemplate = String.join(System.lineSeparator(), lines.subList(1, lines.size()));
        return new Template(subjectTemplate, bodyTemplate);
    }

    private PreparedEmail prepareEmail(Contact contact, String subjectTemplate, String bodyTemplate) {
        String name = safe(contact.getName());
        String email = safe(contact.getEmail());
        String city = safe(contact.getCity());

        String subject = replacePlaceholders(subjectTemplate, name, email, city);
        String body = replacePlaceholders(bodyTemplate, name, email, city);
        return new PreparedEmail(subject, body);
    }

    private String replacePlaceholders(String template, String name, String email, String city) {
        return safe(template)
                .replace("{name}", name)
                .replace("{email}", email)
                .replace("{city}", city);
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }

    private void generatePreviewFiles(List<String> recipients,
                                      Set<String> blacklist,
                                      Map<String, Contact> contactsByEmail,
                                      Template template) throws IOException {
        Path outboxDir = Paths.get("outbox");
        Files.createDirectories(outboxDir);

        Session previewSession = Session.getInstance(new Properties());
        int counter = 0;
        for (String recipientEmail : recipients) {
            String key = recipientEmail.toLowerCase();
            if (blacklist.contains(key)) {
                continue;
            }

            Contact contact = contactsByEmail.get(key);
            if (contact == null) {
                continue;
            }

            try {
                PreparedEmail email = prepareEmail(contact, template.subjectTemplate, template.bodyTemplate);
                String fileName = "to_" + sanitizeFilePart(recipientEmail) + "_" + counter + ".eml";
                MimeMessage mimeMessage = buildMimeMessage(previewSession, "preview@local", recipientEmail, email.subject, email.body);
                byte[] emlBytes = toRfc822Bytes(mimeMessage);
                Files.write(outboxDir.resolve(fileName), emlBytes);
                counter++;
            } catch (MessagingException | IOException e) {
                System.err.println("Preview skipped for " + recipientEmail + ": " + e.getMessage());
            }
        }
    }

    public void sendAllEmails(List<String> recipients,
                              Set<String> blacklist,
                              Map<String, Contact> contactsByEmail,
                              Template template,
                              Path logFile) throws IOException {
        Properties smtpProps = loadMailProperties();
        String username = requireProperty(smtpProps, "mail.username");
        String password = requireProperty(smtpProps, "mail.password");
        long minSendIntervalMs = loadIntervalProperty(smtpProps, "mail.send.minIntervalMs", MIN_SEND_INTERVAL_MS, MIN_SEND_INTERVAL_MS);
        long retryIntervalMs = loadIntervalProperty(smtpProps, "mail.retry.intervalMs", RETRY_INTERVAL_MS, 0);
        Session session = createMailSession(smtpProps, username, password);

        if (logFile.getParent() != null) {
            Files.createDirectories(logFile.getParent());
        }

        long lastSendStartNanos = 0L;
        for (String recipientEmail : recipients) {
            String normalizedRecipient = recipientEmail.trim().toLowerCase();
            if (blacklist.contains(normalizedRecipient)) {
                appendLog(logFile, new SendLog(Instant.now(), recipientEmail, "", "SKIPPED", "SKIPPED (blacklisted)"));
                continue;
            }

            Contact contact = contactsByEmail.get(normalizedRecipient);
            if (contact == null) {
                appendLog(logFile, new SendLog(Instant.now(), recipientEmail, "", "FAILED", "contact not found"));
                continue;
            }

            PreparedEmail preparedEmail = prepareEmail(contact, template.subjectTemplate, template.bodyTemplate);
            boolean sent = false;
            String failureReason = "";

            for (int attempt = 0; attempt <= MAX_RETRIES; attempt++) {
                try {
                    lastSendStartNanos = enforceSendRateLimit(lastSendStartNanos, minSendIntervalMs);

                    MimeMessage message = buildMimeMessage(session, username, recipientEmail, preparedEmail.subject, preparedEmail.body);
                    Transport.send(message);
                    appendLog(logFile, new SendLog(Instant.now(), recipientEmail, preparedEmail.subject, "SUCCESS", ""));
                    sent = true;
                    break;
                } catch (MessagingException e) {
                    failureReason = e.getMessage() == null ? e.getClass().getSimpleName() : e.getMessage();
                    if (attempt < MAX_RETRIES) {
                        sleepSafely(retryIntervalMs);
                    }
                }
            }

            if (!sent) {
                appendLog(logFile, new SendLog(Instant.now(), recipientEmail, preparedEmail.subject, "FAILED", failureReason));
            }
        }
    }

    private Properties loadMailProperties() throws IOException {
        Properties properties = new Properties();
        try (InputStream in = Thread.currentThread().getContextClassLoader().getResourceAsStream("mail.properties")) {
            if (in == null) {
                throw new IOException("Cannot find mail.properties in classpath.");
            }
            properties.load(in);
        }
        requireProperty(properties, "mail.smtp.host");
        requireProperty(properties, "mail.smtp.port");
        requireProperty(properties, "mail.username");
        requireProperty(properties, "mail.password");
        properties.putIfAbsent("mail.smtp.auth", "true");
        properties.putIfAbsent("mail.smtp.starttls.enable", "true");
        return properties;
    }

    private Session createMailSession(Properties smtpProps, String username, String password) {
        return Session.getInstance(smtpProps, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
    }

    private String requireProperty(Properties properties, String key) {
        String value = properties.getProperty(key);
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException("Missing required property: " + key);
        }
        return value.trim();
    }

    private long enforceSendRateLimit(long lastSendStartNanos, long minIntervalMs) {
        if (lastSendStartNanos <= 0L) {
            return System.nanoTime();
        }

        long minIntervalNanos = TimeUnit.MILLISECONDS.toNanos(minIntervalMs);
        long nextAllowedStartNanos = lastSendStartNanos + minIntervalNanos;
        long now = System.nanoTime();

        while (now < nextAllowedStartNanos) {
            sleepPreciselyNanos(nextAllowedStartNanos - now);
            now = System.nanoTime();
        }
        return now;
    }

    private void sleepPreciselyNanos(long nanos) {
        if (nanos <= 0L) {
            return;
        }
        LockSupport.parkNanos(nanos);
        if (Thread.currentThread().isInterrupted()) {
            throw new IllegalStateException("Interrupted while waiting.");
        }
    }

    private long loadIntervalProperty(Properties properties,
                                      String key,
                                      long defaultValue,
                                      long minValue) {
        String raw = properties.getProperty(key);
        if (raw == null || raw.trim().isEmpty()) {
            return defaultValue;
        }
        try {
            long parsed = Long.parseLong(raw.trim());
            if (parsed < minValue) {
                throw new IllegalArgumentException("Property " + key + " must be >= " + minValue + " ms.");
            }
            return parsed;
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Property " + key + " must be a valid integer milliseconds value.", e);
        }
    }

    private void sleepSafely(long millis) {
        try {
            Thread.sleep(millis);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Interrupted while waiting.", e);
        }
    }

    private MimeMessage buildMimeMessage(Session session,
                                         String from,
                                         String to,
                                         String subject,
                                         String body) throws MessagingException {
        MimeMessage message = new MimeMessage(session);
        message.setFrom(new InternetAddress(from));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to, false));
        message.setSubject(subject, StandardCharsets.UTF_8.name());
        message.setText(body, StandardCharsets.UTF_8.name());
        message.setSentDate(new java.util.Date());
        return message;
    }

    private byte[] toRfc822Bytes(MimeMessage message) throws IOException, MessagingException {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            message.saveChanges();
            message.writeTo(out);
            return out.toByteArray();
        }
    }

    private void appendLog(Path logFile, SendLog log) throws IOException {
        Files.writeString(logFile,
                log.toCsvLine() + System.lineSeparator(),
                StandardCharsets.UTF_8,
                java.nio.file.StandardOpenOption.CREATE,
                java.nio.file.StandardOpenOption.APPEND);
    }

    private String sanitizeFilePart(String raw) {
        if (raw == null || raw.isBlank()) {
            return "unknown";
        }
        return raw.replaceAll("[\\\\/:*?\"<>|]", "_");
    }

    private static class CliArgs {
        private String emailListFile;
        private String contactsCsvFile;
        private String templateFile;
        private boolean previewMode;
        private boolean sendMode;
        private String logFile;
        private String blacklistFile;
    }

    private static class Template {
        private final String subjectTemplate;
        private final String bodyTemplate;

        private Template(String subjectTemplate, String bodyTemplate) {
            this.subjectTemplate = subjectTemplate;
            this.bodyTemplate = bodyTemplate;
        }
    }

    private static class PreparedEmail {
        private final String subject;
        private final String body;

        private PreparedEmail(String subject, String body) {
            this.subject = subject;
            this.body = body;
        }
    }
}
